ENV["FOOBARA_ENV"] = "test"

require "bundler/setup"

unless ENV["SKIP_PRY"] == "true" || ENV["CI"] == "true"
  require "pry"
  require "pry-byebug"
end

require "rspec/its"
require "simplecov"

SimpleCov.root "#{__dir__}/../../../"
SimpleCov.command_name "command_connectors"
SimpleCov.coverage_dir "coverage/command_connectors"

SimpleCov.start do
  add_filter "spec/support/"
  # This avoids printing out info about coverage generated by HTTPFormatter
  formatter Class.new { def format(_result) = nil }
end

require "foobara/all"
require "foobara/command_connectors"

RSpec.configure do |config|
  # Need to do :all instead of :each because for specs that use .around,
  # .after(:each) do |example| here is called after example.run but before any threads created in
  # .around might have been cleaned up.
  config.after(:suite) do
    expect(Thread.list.size).to eq(1)
  end
  config.filter_run_when_matching :focus

  # Enable flags like --only-failures and --next-failure
  config.example_status_persistence_file_path = ".rspec_status"

  # Disable RSpec exposing methods globally on `Module` and `main`
  config.disable_monkey_patching!

  config.order = :defined

  config.expect_with :rspec do |c|
    c.syntax = :expect
  end

  # config.raise_errors_for_deprecations!
end

require "foobara/spec_helpers/all"
Dir["#{__dir__}/support/**/*.rb"].each { |f| require f }
