ENV["FOOBARA_ENV"] = "test"

require "bundler/setup"

unless ENV["SKIP_PRY"] == "true" || ENV["CI"] == "true"
  require "pry"
  require "pry-byebug"
end

require "rspec/its"
require "simplecov"

SimpleCov.root "#{__dir__}/../../../"
SimpleCov.command_name "typesystem"
SimpleCov.coverage_dir "coverage/typesystem"

SimpleCov.start do
  add_filter "spec/support/"
  # This avoids printing out info about coverage generated by HTTPFormatter
  formatter Class.new { def format(_result) = nil }
end

project_path = "#{__dir__}/.."

require "foobara/delegate"

# TODO: seems like projects should register themselves as projects via their lib/foobara/whatever file
Foobara.projects("concerns",
                 "enumerated",
                 "callback",
                 "state_machine",
                 "namespace",
                 "domain",
                 "common",
                 "value",
                 "types",
                 "type_declarations",
                 "builtin_types",
                 project_path:)

RSpec.configure do |config|
  config.filter_run_when_matching :focus

  # Enable flags like --only-failures and --next-failure
  config.example_status_persistence_file_path = ".rspec_status"

  # Disable RSpec exposing methods globally on `Module` and `main`
  config.disable_monkey_patching!

  config.order = :defined

  config.expect_with :rspec do |c|
    c.syntax = :expect
  end

  # config.raise_errors_for_deprecations!
end

require "foobara/spec_helpers/all"
Dir["#{__dir__}/support/**/*.rb"].each { |f| require f }
