ENV["FOOBARA_ENV"] = "test"

require "bundler/setup"

if ENV["RUBY_DEBUG"] == "true"
  require "debug"
elsif ENV["SKIP_PRY"] != "true" && ENV["CI"] != "true"
  require "pry"
  require "pry-byebug" unless ENV["SKIP_BYEBUG"] == "true"
end

require "rspec/its"
require "simplecov"

SimpleCov.root "#{__dir__}/../../../"
SimpleCov.command_name "entities"
SimpleCov.coverage_dir "coverage/entities"

SimpleCov.start do
  enable_coverage :branch
  add_filter "spec/support/"
  # This avoids printing out info about coverage generated by HTTPFormatter
  formatter Class.new { def format(_result) = nil }
end

require "foobara/project"
require "foobara/delegate"
require "foobara/builtin_types"
require "foobara/entity"
require "foobara/in_memory_crud_driver"
require "foobara/model_attribute_helpers"
require "foobara/nested_transactionable"

Foobara.install!

RSpec.configure do |config|
  config.filter_run_when_matching :focus

  # Enable flags like --only-failures and --next-failure
  config.example_status_persistence_file_path = ".rspec_status"

  # Disable RSpec exposing methods globally on `Module` and `main`
  config.disable_monkey_patching!

  config.order = :defined

  config.expect_with :rspec do |c|
    c.syntax = :expect
  end

  # config.raise_errors_for_deprecations!
end

require "foobara/spec_helpers/all"
Dir["#{__dir__}/support/**/*.rb"].each { |f| require f }
