require "active_support/concern"
require "active_support/core_ext/array/wrap"
require "active_support/core_ext/hash/indifferent_access"
require "active_support/core_ext/module/delegation"
require "active_support/core_ext/string/inflections"

# TODO: break these out into separate gems instead of simulating it here
require "foobara/common"
require "foobara/value"
require "foobara/enumerated"
require "foobara/callback"
require "foobara/state_machine"
require "foobara/types"
require "foobara/type_declarations"
require "foobara/builtin_types"
require "foobara/command"
require "foobara/domain"
