name: Lint

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - name: set ruby version
        run: |
          echo ruby_version=`cat .ruby-version` >> "$GITHUB_ENV"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
